app_backend_dashboard:
    path: /
    defaults:
        _controller:  App\Controller\DashboardController::indexAction
        template:     'backend/index.html.twig'

app_backend_partial:
    resource: "partial.yaml"
    prefix: /_partial

sylius_backend_admin_user:
    resource: "admin_user.yaml"

sylius_backend_customer:
    resource: "customer.yaml"

sylius_backend_security:
    resource: "security.yaml"

app_backend_product_category:
    resource: "shop_product_category.yaml"

app_backend_product_attribute:
    resource: "shop_product_attribute.yaml"

app_backend_product_attribute_value:
    resource: "shop_product_attribute_value.yaml"

app_backend_product_brand:
    resource: "shop_product_brand.yaml"

app_backend_product_product:
    resource: "shop_product_product.yaml"
