app_backend_product_attribute:
    resource: |
        alias: app.product.attribute
        section: backend
        except: ['show']
        redirect: update
        grid: app_backend_product_attribute
        vars:
            all:
                subheader: app.ui.manage_articles
            index:
                icon: newspaper
        templates: backend/crud
    type: sylius.resource